# Generated by Django 4.1.2 on 2022-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('resolution', models.CharField(blank=True, max_length=12, null=True, verbose_name='Resolution')),
                ('diagonal', models.FloatField(blank=True, null=True, verbose_name='Diagonal')),
            ],
        ),
    ]
